#### This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # For data visualization

df = pd.read_csv('/kaggle/input/beartwo/oasisctf.csv')
df.head()

/tmp/ipykernel_19/1478662828.py:5: DtypeWarning: Columns (1,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/kaggle/input/beartwo/oasisctf.csv')

   S NO                  CATS      SCORE       TUNE CATEGORY VAL
0     1                 Lykoi  41.843255  22.552631        D   p
1     2  Norweigan Forest Cat  23.902451  82.061124        B   g
2     3            Sphynx Cat  38.751703  94.895799        E   Q
3     4         Scottish Fold   1.130913  62.180388        C   a
4     5            Sphynx Cat  37.354027  41.193846        D   L

In [2]:
flag = df.sort_values(by='TUNE', ascending=False).head(13)
flag

      S NO                  CATS      SCORE       TUNE CATEGORY VAL
7160  7161    American Shorthair  17.704750  99.975820        D   O
6718  6719            Sphynx Cat  16.537291  99.974140        C   A
2712  2713            Ocicat Cat  42.098400  99.973701        C   S
4450  4451  Norweigan Forest Cat  45.291105  99.967065        C   I
5667  5668                 Lykoi  11.217710  99.949576        C   S
9698  9699            Sphynx Cat  42.774200  99.944656        D   {
2464  2465            Ocicat Cat  28.706596  99.926038        C   T
2630  2631         Scottish Fold  29.959793  99.920626        D   R
5393  5394    American Shorthair  42.763981  99.920123        B   O
1580  1581          Munchkin Cat   2.683245  99.915939        E   J
3235  3236                 Lykoi   2.138348  99.907399        A   A
2828  2829        Ragamuffin Cat   4.999877  99.905925        A   N
9614  9615          Munchkin Cat  42.751970  99.897092        C   }